export const FUND_CASH_CONTRIBUTION_MIN_AMOUNT = 10_000;
export const FUND_CASH_NOTE_MIN_LENGTH = 5;
export const FUND_CASH_NOTE_MAX_LENGTH = 2000;
export const FUND_CASH_MEMBER_FORCE_SEARCH_MIN = 24;
export const FUND_CASH_MEMBER_SEARCH_MIN_CHARS = 2;
export const FUND_CASH_MEMBER_MAX_VISIBLE = 60;
